title: Student ID 5MJ19ZTHY
# logo: add an image address here (demo had /assets/img/headshot_circle.png)
# description: text below image
# show_downloads: true
# pick your theme through http:s//pages.github.com/themes/
theme: jekyll-theme-minimal
